### ISSUE TITLE
Possível erro de conflito

### ISSUE THREAD

**Issue by CampioniMan** [alexerr400/EditorTexto#1]
No GitHub há a possibilidade de ocorrerem conflitos durante um projeto e este é o caso!

Aqui vão alguns passos para facilitar o processo
### Passos
- Adicione um arquivo ao projeto chamado ".gitignore"
- Edite-o e coloque o seguinte código:<br>
  `ipch/`<br>
  `Debug/`<br>
  `Editor/Debug/`<br>
  `Editor/*.suo`<br>
- Depois disso vá no git bash do repositório e digite:<br>
  `git add .gitignore`
- Após todos esses passos digite os seguintes comandos no git bash do repositório:<br>
  `git rm -r --cached ipch`<br>
  `git rm -r --cached Debug`<br>
  `git rm -r --cached Editor/Debug`<br>

Pronto! Já está tudo praticamente 'anti-conflitos'! Qualquer erro adicione um comentário.

**Comment by alexerr400** [comment]
muito obrigado pela ajuda fazendo esse negocio que ajudou na resolucao do nosso humilde projeto de TOO
